/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.abdurkhalid.ems;

import javax.swing.JOptionPane;
import static me.abdurkhalid.ems.EmployeeTable.employeeTable;

/**
 *
 * @author root
 */
public class DisplayEmployeeInfoTable extends javax.swing.JFrame {
    /**
     * Creates new form DisplayEmployeeInfoTable
     */
    public DisplayEmployeeInfoTable() {
        initComponents();
        DisplayEmployeeInfoTable emp = new DisplayEmployeeInfoTable();
        HourlyWage.setVisible(false);
        HoursPerWeek.setVisible(false);
        WeeksPerYear.setVisible(false);
        HW.setVisible(false);
        HPW.setVisible(false);
        WPY.setVisible(false);
    }
    public void DisplayPTInfo(){
    try{
    int grabbingEmployeeNumber = (int) employeeTable.getValueAt(employeeTable.getSelectedRow(),0);
    EmployeeInfo employeeInquiry = mainjframe.theHash.searchTableEnum(grabbingEmployeeNumber);
    PartTimeEmployee employeeInquiry2 = (PartTimeEmployee) employeeInquiry;
    HourlyWage.setVisible(true);
    HoursPerWeek.setVisible(true);
    WeeksPerYear.setVisible(true);
    HW.setVisible(true);
    HPW.setVisible(true);
    WPY.setVisible(true);
    EN.setText(Integer.toString(employeeInquiry2.getEmployeeNumber()));
    FN.setText(employeeInquiry2.getEmployeeFirstName());
    LN.setText(employeeInquiry2.getEmployeeLastName());
    SX.setText(Integer.toString(employeeInquiry2.getEmployeeSex()));
    WL.setText(Integer.toString(employeeInquiry2.getEmployeeWorkLocation()));
    DR.setText(Double.toString(employeeInquiry2.getDeductionRate()));
    SAL.setText(Double.toString(employeeInquiry2.calcDeductions(employeeInquiry.getDeductionRate())));
    HW.setText(Double.toString(employeeInquiry2.getHourlyWage()));
    HPW.setText(Double.toString(employeeInquiry2.getHoursPerWeek()));
    WPY.setText(Double.toString(employeeInquiry2.getWeeksPerYear()));
    }
    catch (Exception m){
    JOptionPane.showMessageDialog(this,"There was an Error Retrieving the employees information!");
    }
    }
    public void DisplayFTInfo(){
    try{
    int grabbingEmployeeNumber = (int) employeeTable.getValueAt(employeeTable.getSelectedRow(),0);
    EmployeeInfo employeeInquiry = mainjframe.theHash.searchTableEnum(grabbingEmployeeNumber);
    FullTimeEmployee employeeInquiry3 = (FullTimeEmployee) employeeInquiry;
    EN.setText(Integer.toString(employeeInquiry3.getEmployeeNumber()));
    FN.setText(employeeInquiry3.getEmployeeFirstName());
    LN.setText(employeeInquiry3.getEmployeeLastName());
    SX.setText(Integer.toString(employeeInquiry3.getEmployeeSex()));
    WL.setText(Integer.toString(employeeInquiry3.getEmployeeWorkLocation()));
    DR.setText(Double.toString(employeeInquiry3.getDeductionRate()));
    SAL.setText(Double.toString(employeeInquiry3.calcDeductions(employeeInquiry3.getDeductionRate())));
    }
    catch (Exception l){
    JOptionPane.showMessageDialog (this,"There was an error retrieving this employees information!");
    }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        title = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        EmployeeNumber = new javax.swing.JLabel();
        Sex = new javax.swing.JLabel();
        WorkLocation = new javax.swing.JLabel();
        DeductionRate = new javax.swing.JLabel();
        HourlyWage = new javax.swing.JLabel();
        HoursPerWeek = new javax.swing.JLabel();
        WeeksPerYear = new javax.swing.JLabel();
        EN = new javax.swing.JLabel();
        FN = new javax.swing.JLabel();
        LN = new javax.swing.JLabel();
        SX = new javax.swing.JLabel();
        WL = new javax.swing.JLabel();
        DR = new javax.swing.JLabel();
        HW = new javax.swing.JLabel();
        HPW = new javax.swing.JLabel();
        WPY = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        editEmployee = new javax.swing.JButton();
        Salary = new javax.swing.JLabel();
        SAL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setText("EmployeeInformation");

        FirstName.setText("First Name");

        LastName.setText("LastName");

        EmployeeNumber.setText("EmployeeNumber");

        Sex.setText("Sex ");

        WorkLocation.setText("WorkLocation");

        DeductionRate.setText("Deduction Rate ");

        HourlyWage.setText("HourlyWage ");

        HoursPerWeek.setText("HoursPerWeek");

        WeeksPerYear.setText("WeeksPerYear");

        EN.setText("EN");

        FN.setText("FN");

        LN.setText("LN");

        SX.setText("SX");

        WL.setText("WL");

        DR.setText("DR");

        HW.setText("HW");

        HPW.setText("HPW");

        WPY.setText("WPY");

        jButton1.setText("Change Type");

        editEmployee.setText("Edit Employee");

        Salary.setText("Salary");

        SAL.setText("SAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EmployeeNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HPW)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(DR)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SX)
                                            .addComponent(WL))))
                                .addComponent(WPY)
                                .addComponent(HW))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FN)
                                    .addComponent(LN))
                                .addGap(10, 10, 10)))
                        .addGap(126, 126, 126))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EN)
                            .addComponent(SAL))
                        .addGap(108, 108, 108))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HoursPerWeek)
                    .addComponent(HourlyWage)
                    .addComponent(WorkLocation)
                    .addComponent(Sex)
                    .addComponent(DeductionRate)
                    .addComponent(WeeksPerYear)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstName)
                            .addComponent(LastName))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Salary)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(editEmployee)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(title)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeNumber)
                    .addComponent(EN, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName)
                    .addComponent(FN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastName)
                    .addComponent(LN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sex)
                    .addComponent(SX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkLocation)
                    .addComponent(WL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeductionRate)
                    .addComponent(DR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salary)
                    .addComponent(SAL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HourlyWage, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoursPerWeek)
                    .addComponent(HPW))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WeeksPerYear)
                    .addComponent(WPY))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEmployee)
                    .addComponent(jButton1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayEmployeeInfoTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayEmployeeInfoTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayEmployeeInfoTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayEmployeeInfoTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayEmployeeInfoTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel DR;
    private javax.swing.JLabel DeductionRate;
    private static javax.swing.JLabel EN;
    private javax.swing.JLabel EmployeeNumber;
    private static javax.swing.JLabel FN;
    private javax.swing.JLabel FirstName;
    private static javax.swing.JLabel HPW;
    private static javax.swing.JLabel HW;
    private javax.swing.JLabel HourlyWage;
    private javax.swing.JLabel HoursPerWeek;
    private static javax.swing.JLabel LN;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel SAL;
    private static javax.swing.JLabel SX;
    private javax.swing.JLabel Salary;
    private javax.swing.JLabel Sex;
    private static javax.swing.JLabel WL;
    private static javax.swing.JLabel WPY;
    private javax.swing.JLabel WeeksPerYear;
    private javax.swing.JLabel WorkLocation;
    private javax.swing.JButton editEmployee;
    private javax.swing.JButton jButton1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
